{
  "hash": "f5c8958683d7940d212b4ff0a33d9009",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Canadian Crop Production for Brewing and Distilling\"\nsubtitle: \"A reproducible SQL analysis of production, yield, prices and exchange rates\"\nauthor: \"Miguelangel Palma Rojas\"\ndate: last-modified\nlang: en\n---\n\n## Business question\n\nCanadian microbreweries and microdistilleries depend on grains whose availability and cost change across provinces and years. This notebook exposes the complete workflow: CSV ingestion, validation, SQLite construction, parameterized SQL, currency conversion, and visualization.\n\n## Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DBI)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(here)\nlibrary(knitr)\nlibrary(RSQLite)\nlibrary(scales)\nlibrary(tibble)\n```\n:::\n\n\n## Read and validate four sources\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrop <- read.csv(here(\"data\", \"annual_crop.csv\"), stringsAsFactors = FALSE)\ndaily_fx <- read.csv(here(\"data\", \"daily_fx.csv\"), stringsAsFactors = FALSE)\nmonthly_fx <- read.csv(here(\"data\", \"monthly_fx.csv\"), stringsAsFactors = FALSE)\nfarm_prices <- read.csv(\n  here(\"data\", \"monthly_farm_prices.csv\"),\n  stringsAsFactors = FALSE\n)\n\ncrop$YEAR <- as.Date(crop$YEAR)\ncrop$YEAR_NUMBER <- as.integer(format(crop$YEAR, \"%Y\"))\ndaily_fx$DATE <- as.Date(daily_fx$DATE)\nmonthly_fx$DATE <- as.Date(monthly_fx$DATE)\nfarm_prices$DATE <- as.Date(farm_prices$DATE)\n\nrequired_crop_columns <- c(\n  \"CD_ID\", \"YEAR\", \"CROP_TYPE\", \"GEO\", \"SEEDED_AREA\",\n  \"HARVESTED_AREA\", \"PRODUCTION\", \"AVG_YIELD\"\n)\nrequired_fx_columns <- c(\"DFX_ID\", \"DATE\", \"FXUSDCAD\")\nrequired_price_columns <- c(\n  \"CD_ID\", \"DATE\", \"CROP_TYPE\", \"GEO\", \"PRICE_PRERMT\"\n)\n\nstopifnot(\n  all(required_crop_columns %in% names(crop)),\n  all(required_fx_columns %in% names(daily_fx)),\n  all(required_fx_columns %in% names(monthly_fx)),\n  all(required_price_columns %in% names(farm_prices)),\n  nrow(crop) > 0,\n  nrow(daily_fx) > 0,\n  nrow(monthly_fx) > 0,\n  nrow(farm_prices) > 0,\n  anyDuplicated(crop$CD_ID) == 0\n)\n\ntibble(\n  table = c(\"crop_data\", \"daily_fx\", \"monthly_fx\", \"farm_prices\"),\n  records = c(\n    nrow(crop),\n    nrow(daily_fx),\n    nrow(monthly_fx),\n    nrow(farm_prices)\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|table       | records|\n|:-----------|-------:|\n|crop_data   |     672|\n|daily_fx    |    1033|\n|monthly_fx  |      50|\n|farm_prices |    2678|\n\n\n:::\n:::\n\n\n## Build SQLite during the render\n\nThe database is temporary, so the repository stores transparent CSV snapshots rather than a binary database.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatabase_path <- tempfile(fileext = \".sqlite\")\nconnection <- dbConnect(SQLite(), database_path)\n\ndbWriteTable(connection, \"crop_data\", crop, overwrite = TRUE)\ndbWriteTable(connection, \"daily_fx\", daily_fx, overwrite = TRUE)\ndbWriteTable(connection, \"monthly_fx\", monthly_fx, overwrite = TRUE)\ndbWriteTable(connection, \"farm_prices\", farm_prices, overwrite = TRUE)\n\ndbListTables(connection)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"crop_data\"   \"daily_fx\"    \"farm_prices\" \"monthly_fx\" \n```\n\n\n:::\n:::\n\n\n## National production trends\n\nThe crop names are passed as bound parameters rather than pasted into SQL.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproduction_sql <- \"\n  SELECT YEAR, CROP_TYPE, PRODUCTION\n  FROM crop_data\n  WHERE GEO = 'Canada'\n    AND CROP_TYPE IN (?, ?, ?)\n  ORDER BY YEAR, CROP_TYPE\n\"\n\nproduction_trends <- dbGetQuery(\n  connection,\n  production_sql,\n  params = list(\"Barley\", \"Rye\", \"Wheat\")\n)\n\nproduction_trends$YEAR <- as.Date(\n  production_trends$YEAR,\n  origin = \"1970-01-01\"\n)\n\nlatest_production <- production_trends |>\n  filter(YEAR == max(YEAR)) |>\n  slice_max(PRODUCTION, n = 1, with_ties = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  production_trends,\n  aes(x = YEAR, y = PRODUCTION, color = CROP_TYPE)\n) +\n  geom_line(linewidth = 0.8) +\n  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +\n  scale_color_viridis_d(end = 0.85) +\n  labs(\n    title = \"Canadian crop production over time\",\n    x = \"Year\",\n    y = \"Production (metric tonnes)\",\n    color = \"Crop\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/production-chart-1.png){fig-alt='Lines showing Canadian barley, rye, and wheat production over time.' width=672}\n:::\n:::\n\n\n## Highest yields in Saskatchewan\n\nGeography, year, and result count are all bound parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyield_sql <- \"\n  SELECT\n    CROP_TYPE,\n    ROUND(AVG(AVG_YIELD), 1) AS average_yield\n  FROM crop_data\n  WHERE GEO = ? AND YEAR_NUMBER = ?\n  GROUP BY CROP_TYPE\n  ORDER BY average_yield DESC\n  LIMIT ?\n\"\n\ntop_yields <- dbGetQuery(\n  connection,\n  yield_sql,\n  params = list(\"Saskatchewan\", 2000L, 6L)\n)\n\ntop_yields |>\n  kable(col.names = c(\"Crop\", \"Average yield\"))\n```\n\n::: {.cell-output-display}\n\n\n|Crop   | Average yield|\n|:------|-------------:|\n|Barley |          2800|\n|Wheat  |          2200|\n|Rye    |          2100|\n|Canola |          1400|\n\n\n:::\n:::\n\n\n## Canola prices in CAD and USD\n\nThe query joins monthly prices and exchange rates by date. Dividing CAD per tonne by CAD per USD produces USD per tonne.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_sql <- \"\n  SELECT\n    p.DATE,\n    p.PRICE_PRERMT AS price_cad_per_tonne,\n    fx.FXUSDCAD,\n    ROUND(p.PRICE_PRERMT / fx.FXUSDCAD, 2) AS price_usd_per_tonne\n  FROM farm_prices p\n  INNER JOIN monthly_fx fx ON p.DATE = fx.DATE\n  WHERE p.CROP_TYPE = 'Canola' AND p.GEO = ?\n  ORDER BY p.DATE DESC\n  LIMIT ?\n\"\n\ncanola_prices <- dbGetQuery(\n  connection,\n  price_sql,\n  params = list(\"Saskatchewan\", 12L)\n)\n\ncanola_prices$DATE <- as.Date(canola_prices$DATE, origin = \"1970-01-01\")\n\ncanola_prices |>\n  slice_head(n = 6) |>\n  kable(\n    col.names = c(\"Date\", \"CAD / tonne\", \"CAD per USD\", \"USD / tonne\"),\n    digits = 2\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Date       | CAD / tonne| CAD per USD| USD / tonne|\n|:----------|-----------:|-----------:|-----------:|\n|2020-12-01 |      507.33|        1.28|      396.11|\n|2020-11-01 |      495.64|        1.31|      379.27|\n|2020-10-01 |      474.80|        1.32|      359.30|\n|2020-09-01 |      463.52|        1.32|      350.41|\n|2020-08-01 |      464.60|        1.32|      351.38|\n|2020-07-01 |      462.88|        1.35|      342.91|\n\n\n:::\n:::\n\n\n## Decision notes\n\n- Production volume provides supply context, not immediately available inventory.\n- Provincial detail matters for procurement decisions.\n- Currency conversion is a dated estimate, not a transaction quote.\n- Transportation, quality, and contracts remain outside this dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbDisconnect(connection)\n```\n:::\n\n\n## Conclusion\n\n- Within the three national series, Wheat has the largest production in 2020, reaching 35,183,000 metric tonnes. This establishes the dominant volume signal in the latest shared year.\n- The parameterized Saskatchewan query ranks Barley first in 2000 with an average yield of 2,800 in the source dataset's reported yield units.\n- For December 2020, canola is 507.33 CAD per tonne. At 1.2808 CAD per USD, the joined estimate is 396.11 USD per tonne.\n- These results support supply and currency monitoring, but not a purchasing decision by themselves: transport costs, quality grades, contract terms, and basis risk are absent from the relational model.\n\nSee the [Spanish version](es/index.qmd).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}